#New input creation 
---
name: prodinit_ippu_textiles_tonne
longname : Initial Industrial Production
sector: IPPU
subsector: ~
units: tonnes
projection: ~
...
#Metadata
---
resources:
  url: https://github.com/milocortes/sisepuede_data/blob/main/IPPU/prodinit_ippu_textiles_tonne/input_to_sisepuede/historical/prodinit_ippu_textiles_tonne.csv
  description: Global  Initial Industrial Production
aditional_information: >
  Textile Mills in Louisiana - current trends and industry outlook (2019-2029)
  https://www.ibisworld.com/us/industry/louisiana/textile-mills/25394/
  U.S. Textile Market Size
  https://www.grandviewresearch.com/industry-analysis/us-textile-market-report#:~:text=The%20U.S.%20textile%20market%20size%20was%20estimated%20at,increasingly%20higher%20importance%20in%20the%20lifestyle%20of%20consumers
Assumptions: >
  The U.S. textile market size was estimated at USD 251.79 billion
  The Louisian textile market size was estimated at USD 59.6 million
  Then the Louisian textile market size is the 0.02 % of the US textile market size
  The Market size is directly related to production
