#New input creation 
---
name: frac_scoe_heat_energy_commercial_municipal_solid_biomass
longname : SCOE Fraction Heat Energy Demand Solid Biomass
sector: Energy
subsector: SCOE
units: ratio [0-1]
projection: ~
...
#Metadata
---
resources:
  url: https://www.eia.gov/state/seds/data.php?incfile=/state/seds/sep_use/com/use_com_LA.html&sid=LA
  description: Table CT5. Commercial Sector Energy Consumption Estimates, 1960-2021, Louisiana
aditional_information: ~
Assumptions: >
  The following energy sources were considered to obtain this Heat Energy Demand Fraction:
  Coal, diesel(DistillateFuel Oil), electricity,gasoline, hydrocarbon gas liquids, kerosene,naturalgas,solid biomass


