#New input creation 
---
name: new_input_test_2
longname : new_input_test_long_name
sector: sector_test_folder
subsector: subsector_test_folder
units: units
projection: 0.1 #~
...
#Metadata
---
resources:
  url: https://www.example.org/
  description: url description
aditional_information: some text in yaml format
Assumptions:
  - Assumption 1
  - Assumption 2



