#New input creation 
---
name: prodinit_ippu_plastic_tonne
longname : Initial Industrial Production
sector: Energy
subsector: SCOE
units: tonnes
projection: ~
...
#Metadata
---
resources:
  url: https://www.epa.gov/ghgemissions/state-ghg-emissions-and-removals
  description: State GHG Emissions and Removals
aditional_information: >
  Louisiana industrial process emissions by sector:
  https://www.lsu.edu/ces/publications/2021/louisiana-2021-greehouse-gas-inventory-df-rev_reduced.pdf
  Inventory of Greenhouse Gases in Louisiana:
  https://www.dnr.louisiana.gov/assets/docs/energy/reports/LA_GHG_inventory_report.pdf
Assumptions: ~