#New input creation 
---
name: consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances
longname : SCOE Initial Per GDP Electric Appliances Energy Consumption
sector: Energy
subsector: SCOE
units: Tera Joule per billion USD
projection: ~
...
#Metadata
---
resources:
  url: https://www.eia.gov/state/seds/seds-data-complete.php?sid=LA
  description: State Energy Data System (SEDS) 1960-2021 (complete)
aditional_information: ~
Assumptions:
  - Appliances and electronics account for about 6.5% of the total electricity consumption in Louisiana
  - 1 Million Kilowatthours = 3.6e+12 Joules and 1 joule = 1e-12 Tera Joules
  - For the calculations, the real GDP was used

