#New input creation 
---
name: prodinit_ippu_wood_tonne
longname : Initial Industrial Production
sector: IPPU
subsector: ~
units: tonnes
projection: ~
...
#Metadata
---
resources:
  url: https://www.srs.fs.usda.gov/pubs/ru/ru_fs425.pdf
  description: Timber Product Output and Use Louisiana 2021
aditional_information: ~
Assumptions: >
  The value for 2021 was replicated for all the years
  1 cubic foot is equal to 0.027864 metric tons (tonnes)
  657,954 thousand cubic feet = 18,333,230.256 tonnes