#New input creation 
---
name: scalar_scoe_heat_energy_demand_other_se
longname : SCOE Heat Energy Demand Scalar
sector: Energy
subsector: SCOE
units: Tera Joule per billion USD
projection: ~
...
#Metadata
---
resources:
  url: https://sisepuede.readthedocs.io/en/latest/energy_non_electric.html
  description: ~
aditional_information: ~
Assumptions: >
  scalar_ should generally be left = 1
  it provides a mechanism to:
  either implement a policy for demand management, or
  in combination with clever elasticities and initial demand states, exogenously specify demand


